apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  type: NodePort
  selector:
    app: python-flask
  ports:
  - protocol: TCP
    port: 80          # Service port
    targetPort: 5000  # Container port
    nodePort: 30080   # External access port